name: Critical files check - pliki projektu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check essential files
      run: |
        echo "Sprawdzanie kluczowych plików..."
        [ -f "main.py" ] || (echo "❌ Brak pliku main.py!" && exit 1)
        [ -f "README.md" ] || (echo "❌ Brak pliku README.md!" && exit 1)
        [ -f "requirements.txt" ] || (echo "⚠️ Brak pliku requirements.txt (opcjonalny, tylko informacja)")
        echo "✅ Kluczowe pliki istnieją (lub są opcjonalne)."
