name: Test Python Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Test game launch
      run: |
        echo "Sprawdzanie czy plik main.py istnieje..."
        test -f main.py
        echo "Test zakończony: plik main.py istnieje."
